print "Starting maya loading and fbx conversion \n";
	
if (`file -q -exists "C:/Users/mgrav/DOCUME~1/GitHub/AZURE-~1/Azure-Bloodmage-final_programming_2/Azure Bloodmage/Assets/Models/CharacterAnim/base_character (1) 1.mb"`)
{		
	file -o "C:/Users/mgrav/DOCUME~1/GitHub/AZURE-~1/Azure-Bloodmage-final_programming_2/Azure Bloodmage/Assets/Models/CharacterAnim/base_character (1) 1.mb";
	FBXExportEmbeddedTextures -v false;
	// FBXExportHardEdges -v true;
	FBXExportApplyConstantKeyReducer -v false;
	FBXExportShowUI -v false;

	print "Before fbx export\n";
	FBXExport -f "C:/Users/mgrav/DOCUME~1/GitHub/AZURE-~1/Azure-Bloodmage-final_programming_2/Azure Bloodmage/Temp/ExportedFBXFile.fbx";
	print "after fbx export\n";
}
else
	print "Could not open Maya file.";

sysFile -delete "C:/Users/mgrav/DOCUME~1/GitHub/AZURE-~1/Azure-Bloodmage-final_programming_2/Azure Bloodmage/Temp/CommandPipe";

$donepipeKill = `fopen "C:/Users/mgrav/DOCUME~1/GitHub/AZURE-~1/Azure-Bloodmage-final_programming_2/Azure Bloodmage/Temp/SyncPipeKill" "w"`;
fwrite $donepipeKill "Done";
fclose $donepipeKill;
